language: node_js

node_js:
  - "7"
  # - "6"
  # - "5"

stages:
  - Install
  - Build
  - Test
  - GitHub release

jobs:
  include:
    - stage: Install
      script: yarn install
    - stage: Build
      script: yarn build
    - stage: Test
      script: yarn test
      # after_success: ./gen_bundle.sh
    - stage: GitHub release
      script: echo "Deploying to GitHub releases"
      deploy:
          provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          skip_cleanup: true
          on:
            tags; true

notifications:
  email:
    recipients:
      - ho.ho@nogle.com
    on_success: always
    on_failure: always
