language: node_js

node_js:
  - "7"
  # - "6"
  # - "5"

stages:
  - install
  - build
  - test

jobs:
  include:
    - stage: install
      script: yarn install
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
      after_success: ./gen_bundle.sh

notifications:
  email:
    recipients:
      - ho.ho@nogle.com
    on_success: always
    on_failure: always
