language: node_js

node_js:
  - "7"
  # - "6"
  # - "5"

stages:
  - install
  - build
  - test

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: install
      script: yarn install
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test

notifications:
  email:
    recipients:
      - ho.ho@nogle.com
    on_success: always
    on_failure: always
