language: node_js
node_js:
- '7'
stages:
- Test
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Test
    before_script: 
    script: scripts/gen_bundle.sh
notifications:
  email:
    recipients:
    - ho.ho@nogle.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: Xc7Q3AqH/EVqyVtimX1QIDrGxVkOl6kX0EgJiNFGsY8phfdqFl8+2ksRL7RnSG23pHEEUCZ/h/N8OOwwhjxpTaLpwckJpLr5F7jOGNQ4RMtjxTa6HXR7DUq0K2MkpFDFGCjGlZDAaocvJKvNG8gXrEVYqmGGXh7ZdDWqUlGZZbuWuwNRoLyB02aiBFFF+g7XOD8tcM6cZyNsmLoPHbqA4Sdl3WApT754gDQqGbhgZ/lLSK40MaTYMvDBGObEk13KaW5y4Riedo+Wq9yIQu5OQgUIyN0AB7IQbzYrU6KVpvumOPA8kQURdsOv1lFr8WhD5eQ8FIijhOfZqGWB0FxZx9zqdd3/s9gI8t7aKWDjCfr4GhDBbSrjIb3lw8rSfLR+dxDf803W+RSUA86uDFjW3HYXla++qHifcKNI1H5Jf2yeIzUfQ6kaF6bHeDI7ufC3NFdl4SMFNPwKK0XPUGdnBtBMdTZ8pyuXVA5Ahr7PJX5pdDs7u/WeeK6PeAUB8dKBG7syy5WGeXKfRr8OBahU6gQjw30CP4FKcUn09kmzPDvRRyuCVor32pJf3MKpij5y7A7BLPQHo93F16bNdFrKGAetcSBKSN/HdeSdayvR0w0LP+/rWnWTspkxenCksJVNuWfzBdm1hrF6ppzDM3JrazXWElbKW4hpfQH/2UZaloE=
