language: node_js
node_js:
- '7'
stages:
- Test
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Test
    before_script: 
      - git config --global user.email "hoho1234578@gmail.com"
      - git config --global user.name "hoho1234578"
    script: scripts/gen_bundle.sh
notifications:
  email:
    recipients:
    - ho.ho@nogle.com
    on_success: always
    on_failure: always