language: node_js
node_js:
- '7'
stages:
- Test
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Test
    before_script: 
    script: scripts/gen_bundle.sh

notifications:
  email:
    recipients:
    - ho.ho@nogle.com
    on_success: always
    on_failure: always
env:
  global:
    secure: i6cNc5IWFtqL7d9FtxxgFvqXn3l98qqfHsQERWB/pIwuiS/oWKS09fv/SE1i5+k2LIaE1i8cxuZmnFJ3NkqER8hxVOXUBpoWsrRV//cbTtGmmI3gklA9bmY+Rhqj7E21xr6BLoc5riOB9I01CxIfri86ry5zEtdyQHU1VHoC59ijlvSH8edgL8OCvOqL8lwcDXIL3kR0hF3Iw+fa1L5vZ6wWs0ITGsilhDJ1mSQaFp/AEdj6pcdCXeyiH5u+HbXyf6kjDVyePN33PdZ940LDdigp4TNRintve9s7T/3y8umPuHDtrX/ta8P941w0aQ8eOHegphEs3T82co5sCTvuHqm+D17Ip8KrBxqQisdSrGW04kS3gEpRgFmJQzEdb98IiZ9U6aeLMTFOtRoA6hhuaeDIjaVs+ftKU0+wpPkeiamnmLLdU1g+A9UYOfZQ2EXQWymIXZ+sWtIqAvoUoz47v0IMyjyfmgqPGEyKiIhZAH0SQ8cwnkvpBvAjMX/2WMZMSmA9/1kZsSsFlZ06KiVySCRGxdDjKDFTSOqJLLlerbC9ANyV21q7fMfd28MTDBT4JzkEfRWnVcFhYzFBYsldpOmfoJnoagNv441gAWqYwECTCFZRwdtvzfyHIZSlvUhr1V9j7+od3Ke+nc9/9R0BonPHqvZDheopA0PKEydo8Jg=
